(custom-set-variables
 '(ediff-diff-options "-w")
 '(font-lock-mode t nil (font-lock))
 '(query-user-mail-address nil)
 '(toolbar-mail-reader 'vm)
 '(user-mail-address "timothy.renner@gmail.com"))
(custom-set-faces
;; '(default ((t (:family "Courier" :foreground "grey" :background "wheat" :size "11pt"))) t)
 '(default ((t (:family "Courier" :foreground "black" :background "wheat" :size "11pt"))) t)
;; '(blue ((t (:foreground "wheat" :background "grey" :size "18"))) t)
 '(blue ((t (:foreground "wheat" :background "black" :size "18"))) t)
;; '(bold ((t (:foreground "grey" :background "wheat" :size "18" :bold t))) t)
 '(bold ((t (:foreground "black" :background "wheat" :size "18" :bold t))) t)
 '(bold-italic ((t (:foreground "black" :background "wheat" :size "18" :bold t :italic t))) t)
 '(custom-face-tag-face ((t (:underline t))))
 '(italic ((t (:size "18" :italic t))) t))

(shell)
(with-current-buffer "*shell*" (rename-buffer "*run*"))
(shell)
(with-current-buffer "*shell*" (rename-buffer "*build*"))
(shell)
(with-current-buffer "*shell*" (rename-buffer "*shell*"))
(set-buffer "*scratch*")
